---
language: python
python: "2.7"
sudo: true

env:
    global:
    - ANSIBLE_ROLES_PATH=/home/travis/build

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - sudo pip install ansible

script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  - curl http://localhost/
